version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "actions/checkout"
      - dependency-name: "aws-actions/configure-aws-credentials"
      - dependency-name: "hashicorp/setup-terraform"
